### ISSUE TITLE
Latest testng 7.8.0 is not working with eclipse testng 7.4.0.202106051955

### ISSUE THREAD

**Issue by ahoehma** [testng-team/testng-eclipse#551]
### Problem Statement

I run a test via testng-eclipse after updated my project testng to 7.8.0 and now its crashing:

[RemoteTestNG] detected TestNG version 7.8.0
java.lang.NoSuchMethodError: 'void org.testng.TestRunner.<init>(org.testng.internal.IConfiguration, org.testng.ISuite, org.testng.xml.XmlTest, boolean, java.util.Collection, java.util.List)'
at org.testng.remote.support.RemoteTestNG6_12$1.newTestRunner(RemoteTestNG6_12.java:33)
at org.testng.remote.support.RemoteTestNG6_12$DelegatingTestRunnerFactory.newTestRunner(RemoteTestNG6_12.java:66)
at org.testng.ITestRunnerFactory.newTestRunner(ITestRunnerFactory.java:52)
at org.testng.SuiteRunner$ProxyTestRunnerFactory.newTestRunner(SuiteRunner.java:720)
at org.testng.SuiteRunner.init(SuiteRunner.java:224)
at org.testng.SuiteRunner.<init>(SuiteRunner.java:116)
at org.testng.TestNG.createSuiteRunner(TestNG.java:1375)
at org.testng.TestNG.createSuiteRunners(TestNG.java:1349)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1191)
at org.testng.TestNG.runSuites(TestNG.java:1114)
at org.testng.TestNG.run(TestNG.java:1082)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)

### The Dependency Management tool for your project

- [X] Maven (M2E aka Eclipse?)
- [ ] Gradle
- [ ] Ant
- [ ] Eclipse Buildpath (aka. Use "TestNG Library" for your project in Eclipse)

### Operating System

- [X] Windows
- [ ] Linux
- [ ] OSX

**Comment by adngzz** [comment]
Also experiencing the same issue, worked fine after downgrading to 7.7.1. I think it must be the plug in as the cases seem to run fine if invoked directly from maven.

**Comment by zanoon2020** [comment]
@adngzz have you found any solution without downgrading ?

**Comment by adngzz** [comment]
> @adngzz have you found any solution without downgrading ?
Not really, but since my project is using maven downgrading is easy. Also it only impacts eclipse running via command line works fine.
I have tracked the error to  https://github.com/testng-team/testng-remote/blob/master/remote6_12/src/main/java/org/testng/remote/support/RemoteTestNG6_12.java line 33

It seem in 2.8 they added an extra parameter(SuiteRunner) in the TestRunner constructor at org.testng.TestRunner which RemoteTestNG6_12 is not sending. I'll post this in that repo as I think the fault ultimately lies in testng-remote.


```
  /* /!\ This constructor is used by testng-remote, any changes related to it please contact with testng-team. */
  public TestRunner(
      IConfiguration configuration,
      ISuite suite,
      XmlTest test,
      boolean skipFailedInvocationCounts,
      Collection<IInvokedMethodListener> invokedMethodListeners,
      List<IClassListener> classListeners,
      SuiteRunner suiteRunner) {
    this.comparator = Systematiser.getComparator();
    init(
        configuration,
        suite,
        test,
        suite.getOutputDirectory(),
        suite.getAnnotationFinder(),
        skipFailedInvocationCounts,
        invokedMethodListeners,
        classListeners,
        suiteRunner);
  }
```

**Comment by adngzz** [comment]
Added case to TestNG remote https://github.com/testng-team/testng-remote/issues/127

**Comment by adngzz** [comment]
It seems the issue over remote was fixed, not sure if this one needs updated references.

**Comment by zanoon2020** [comment]
@adngzz i still face the same issue , not sure what i should update ?

**Comment by adngzz** [comment]
> @adngzz i still face the same issue , not sure what i should update ?

You could try compiling testng-remote and replace the jar in your eclipse install, but I am not familiar with the project and haven't checked for any other dependencies. Otherwise you'll have to wait for a formal release i guess.

**Comment by missedone** [comment]
Pls try with the latest plugin version now

**Comment by zanoon2020** [comment]
@missedone thanks a lot now working
